port: 2222
inet: 0.0.0.0
sock: /tmp/router.sock
mbus: nats://localhost:4222
logging:
  level: info
pid: /var/vcap/sys/run/router.pid

# Used for /healthz and /vars endpoints. If not provided random
# values will be generated on component start. Uncomment to use 
# static values.
#status:
#  port: 34503
#  user: thin
#  password: thin
